version: '3'

services:

  db:
    image: postgres:15.0-alpine
    restart: always
    container_name: devStorage
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'db_app'
    ports:
      - '5451:5432'
