# Generated by Django 4.2.7 on 2023-11-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripeapp", "0002_discount_tax_alter_item_price_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="applies_to",
        ),
        migrations.AddField(
            model_name="discount",
            name="duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("once", "Once"),
                    ("repeating", "Repeat"),
                    ("forever", "Forever"),
                ],
                default="once",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="duration_in_months",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Set of key-value pairs that you can attach to an object.This can be useful for storing additional information about the object in a structured format",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tax",
            name="jurisdiction",
            field=models.CharField(
                blank=True,
                help_text="The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tax",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Two-letter country code (ISO 3166-1 alpha-2)",
                null=True,
            ),
        ),
    ]
