# Generated by Django 4.2.7 on 2023-11-30 19:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripeapp", "0003_remove_discount_applies_to_discount_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="redeem_by",
            field=models.DateTimeField(
                blank=True,
                help_text="The max_redemptions and redeem_by values apply to the coupon across every application. For example, you can restrict a coupon to the first 50 usages of it, or you can make a coupon expire by a certain date.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(2028, 11, 28, 19, 39, 7, 627087)
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tax",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Two-letter country code (ISO 3166-1 alpha-2)",
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(2),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="percentage",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=100,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.",
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(2),
                ],
            ),
        ),
    ]
