# Generated by Django 4.2.7 on 2023-12-01 00:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripeapp", "0004_tax_metadata_alter_discount_metadata_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="discounts",
            new_name="discount",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="taxes",
            new_name="tax",
        ),
        migrations.AlterField(
            model_name="discount",
            name="redeem_by",
            field=models.DateTimeField(
                blank=True,
                help_text="The max_redemptions and redeem_by values apply to the coupon across every application. For example, you can restrict a coupon to the first 50 usages of it, or you can make a coupon expire by a certain date.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2028,
                            11,
                            29,
                            0,
                            34,
                            26,
                            405567,
                        )
                    )
                ],
            ),
        ),
    ]
